### ISSUE TITLE
Bug report: Image soruce Bad Signature

### ISSUE THREAD

**Issue by miyago9267** [andy010629/andy010629#1]
## 問題描述
如圖 圖片顯示有誤
點進去顯示Bad Signature

<img width="894" alt="image" src="https://github.com/andy010629/andy010629/assets/55224813/5cb6e894-cf54-4b34-a934-d4bc3f8c37c9">

## 觸發時機
常駐發生

**Comment by andy010629** [comment]
現在才發現這個 Issue XD
